CREATE TABLE disease_group ( id INTEGER PRIMARY KEY, name TEXT NOT NULL );
CREATE TABLE disease_group_properties ( disease_group_id INTEGER NOT NULL, property TEXT NOT NULL, value TEXT, UNIQUE (disease_group_id, property), FOREIGN KEY(disease_group_id) REFERENCES disease_group(id) );
CREATE INDEX disease_group_properties_fk_disease_group_id_property ON disease_group_properties (disease_group_id, property);
CREATE TABLE disease ( id INTEGER PRIMARY KEY, name TEXT NOT NULL, disease_group_id INTEGER NOT NULL, FOREIGN KEY(disease_group_id) REFERENCES disease_group(id) );
CREATE INDEX disease_fk_disease_group_id ON disease (disease_group_id);
CREATE TABLE disease_properties ( disease_id INTEGER NOT NULL, property TEXT NOT NULL, value TEXT, UNIQUE (disease_id, property), FOREIGN KEY(disease_id) REFERENCES disease(id) );
CREATE INDEX disease_properties_fk_disease_id_property ON disease_properties (disease_id, property);
CREATE TABLE patient_subgroup ( id INTEGER PRIMARY KEY, name TEXT, disease_id INTEGER, FOREIGN KEY(disease_id) REFERENCES disease(id) );
CREATE INDEX patient_subgroup_fk_disease_id ON patient_subgroup (disease_id);
CREATE TABLE gene ( id INTEGER PRIMARY KEY, gene_symbol TEXT UNIQUE, ensembl_id TEXT, uniprot_id TEXT );
CREATE TABLE study ( id INTEGER PRIMARY KEY, geo_arrayexpress_code TEXT UNIQUE );
CREATE TABLE drug ( id INTEGER PRIMARY KEY, name TEXT );
CREATE TABLE supporting_sources ( id VARCHAR(256) NOT NULL PRIMARY KEY, pubmed_id INTEGER, doi VARCHAR(4096) );
CREATE TABLE patient ( id INTEGER PRIMARY KEY, patient_subgroup_id INTEGER, study_id INTEGER, FOREIGN KEY(patient_subgroup_id) REFERENCES patient_subgroup(id), FOREIGN KEY(study_id) REFERENCES study(id) );
CREATE INDEX patient_fk_patient_subgroup_id ON patient (patient_subgroup_id);
CREATE INDEX patient_fk_study_id ON patient (study_id);
CREATE TABLE patient_drug_maps ( id INTEGER PRIMARY KEY, patient_id INTEGER, drug_id INTEGER, regulation_sign INTEGER, FOREIGN KEY(patient_id) REFERENCES patient(id), FOREIGN KEY(drug_id) REFERENCES drug(id) );
CREATE INDEX patient_drug_maps_fk_patient_id ON patient_drug_maps (patient_id);
CREATE INDEX patient_drug_maps_fk_drug_id ON patient_drug_maps (drug_id);
CREATE TABLE patient_gene_maps ( id INTEGER PRIMARY KEY, patient_id INTEGER, gene_id INTEGER, regulation_sign INTEGER, FOREIGN KEY(patient_id) REFERENCES patient(id), FOREIGN KEY(gene_id) REFERENCES gene(id) );
CREATE INDEX patient_gene_maps_fk_patient_id ON patient_gene_maps (patient_id);
CREATE INDEX patient_gene_maps_fk_gene_id ON patient_gene_maps (gene_id);
CREATE TABLE patient_graph ( id INTEGER PRIMARY KEY, patient_a_id INTEGER, patient_b_id INTEGER, interaction_sign INTEGER, FOREIGN KEY(patient_a_id) REFERENCES patient(id), FOREIGN KEY(patient_b_id) REFERENCES patient(id) );
CREATE INDEX patient_graph_fk_patient_a_id ON patient_graph (patient_a_id);
CREATE INDEX patient_graph_fk_patient_b_id ON patient_graph (patient_b_id);
CREATE TABLE disease_digraph ( id INTEGER PRIMARY KEY, disease_a_id INTEGER, disease_b_id INTEGER, relative_risk DOUBLE PRECISION, FOREIGN KEY(disease_a_id) REFERENCES disease(id), FOREIGN KEY(disease_b_id) REFERENCES disease(id) );
CREATE INDEX disease_digraph_fk_disease_a_id ON disease_digraph (disease_a_id);
CREATE INDEX disease_digraph_fk_disease_b_id ON disease_digraph (disease_b_id);
CREATE TABLE disease_digraph_properties ( disease_digraph_id INTEGER NOT NULL, property TEXT NOT NULL, value TEXT, UNIQUE (disease_digraph_id,property), FOREIGN KEY (disease_digraph_id) REFERENCES disease_digraph(id) );
CREATE INDEX disease_digraph_properties_fk_disease_digraph_id_property ON disease_digraph_properties (disease_digraph_id, property);
CREATE TABLE patient_subgroup_digraph ( id INTEGER PRIMARY KEY, patient_subgroup_a_id INTEGER, patient_subgroup_b_id INTEGER, relative_risk DOUBLE PRECISION, FOREIGN KEY(patient_subgroup_a_id) REFERENCES patient_subgroup(id), FOREIGN KEY(patient_subgroup_b_id) REFERENCES patient_subgroup(id) );
CREATE INDEX patient_subgroup_digraph_fk_patient_subgroup_a_id ON patient_subgroup_digraph (patient_subgroup_a_id);
CREATE INDEX patient_subgroup_digraph_fk_patient_subgroup_b_id ON patient_subgroup_digraph (patient_subgroup_b_id);
CREATE TABLE patient_subgroup_drug_intersect ( id INTEGER PRIMARY KEY, patient_subgroup_id INTEGER, drug_id INTEGER, regulation_sign INTEGER, FOREIGN KEY(patient_subgroup_id) REFERENCES patient_subgroup(id), FOREIGN KEY(drug_id) REFERENCES drug(id) );
CREATE INDEX patient_subgroup_drug_intersect_fk_patient_subgroup_id ON patient_subgroup_drug_intersect (patient_subgroup_id);
CREATE INDEX patient_subgroup_drug_intersect_fk_drug_id ON patient_subgroup_drug_intersect (drug_id);
CREATE TABLE patient_subgroup_gene_intersect ( id INTEGER PRIMARY KEY, patient_subgroup_id INTEGER, gene_id INTEGER, regulation_sign INTEGER, FOREIGN KEY(patient_subgroup_id) REFERENCES patient_subgroup(id), FOREIGN KEY(gene_id) REFERENCES gene(id) );
CREATE INDEX patient_subgroup_gene_intersect_fk_patient_subgroup_id ON patient_subgroup_gene_intersect (patient_subgroup_id);
CREATE INDEX patient_subgroup_gene_intersect_fk_gene_id ON patient_subgroup_gene_intersect (gene_id);
